### ISSUE TITLE
【素材未提供】分辨率适配请求：2560*1600

### ISSUE THREAD

**Issue by Emirie923** [Nigh/Genshin-fishing#1]
求大佬适配2560*1600分辨率

**Comment by Nigh** [comment]
@Emirie923 提供一下包含浮漂条的钓鱼界面的截图，因为我没有2k屏幕，没法自己截图

**Comment by Emirie923** [comment]
截图太大了 放不了附件 丢的网盘
链接：https://pan.baidu.com/s/1VKJVrAWDqltOyyBlH6adfQ&nbsp;
提取码：yyds&nbsp;
--来自百度网盘超级会员V2的分享





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nigh/Genshin-fishing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nigh/Genshin-fishing] 求大佬适配2560*1600分辨率 (#1)





 
@Emirie923 提供一下包含浮漂条的钓鱼界面的截图，因为我没有2k屏幕，没法自己截图
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nigh** [comment]
@Emirie923 请参考 #9 提供素材。

**Comment by Nigh** [comment]
因长时间未给出素材，故关闭此issue.
