### ISSUE TITLE
自动更新报错(msxml3.dll拒绝访问)

### ISSUE THREAD

**Issue by Nigh** [Nigh/Genshin-fishing#11]
<img width="168" alt="顺便问问这个错误的解决办法" src="https://user-images.githubusercontent.com/1407471/134323130-6dda39fb-34c0-43fa-96df-23928f59b733.png">

**Comment by Nigh** [comment]
### 尝试
打开你的ie浏览器，右上角小齿轮进设置->internet选项->安全->受信任的站点->站点，然后添加https://download.fastgit.org 这个网站。
@FirerainML

**Comment by FirerainML** [comment]
大佬，我这个还是没法解决，而且错误提示也变了。。。这个是只影响自动更新是吗？
![image](https://user-images.githubusercontent.com/89842936/134324127-5b74b9d7-6727-49f2-8461-004dbdc13070.png)

**Comment by Nigh** [comment]
可以在配置中添加`autoupdate=0`来禁用掉自动更新。

**Comment by FirerainML** [comment]
好的，那就没什么问题了，谢谢大佬帮助

**Comment by Nigh** [comment]
@FirerainML
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7209940/GenshinFishing.zip)
试试这个版本，更换了`ServerXMLHTTP`方法。看看能不能解决这个问题。

**Comment by FirerainML** [comment]
可以的！这个没有问题！谢谢大佬！！！

**Comment by Nigh** [comment]
好的，那我会把这个更新加入下个版本。到目前为止，包括你，也就两个人报过这个错。

**Comment by FirerainML** [comment]
辛苦了，这个报错我也不知道是啥原因，百度了也没看懂，估计是网络防火墙之类的？不过大佬能解决这问题真的是太好了哈哈哈
