### ISSUE TITLE
分辨率请求：1280×720

### ISSUE THREAD

**Issue by Magic-boss** [Nigh/Genshin-fishing#2]
内存仅仅8g，害怕.jpg

**Comment by Nigh** [comment]
请提供你需要适配的分辨率。

**Comment by Nigh** [comment]
你也可以选择调低渲染精度。也能很好的通过牺牲画质来提升性能。

**Comment by Magic-boss** [comment]
1280×720的画质，挂机钓鱼足矣（doge）
精度已经是0.6了，呜呜呜
想问问楼主，这个是用啥计算的
cpu还是gpu

**Comment by Magic-boss** [comment]
小声bb：虽然发现并不能占用多少性能，但边钓鱼边敲代码岂不美哉

**Comment by Nigh** [comment]
> 小声bb：虽然发现并不能占用多少性能，但边钓鱼边敲代码岂不美哉

原神只能在前台接受输入，切窗口了输入就无效了。
