### ISSUE TITLE
Bot doesn't react to text appearing when fish bites

### ISSUE THREAD

**Issue by Dramorian** [Nigh/Genshin-fishing#24]
Ofter it misses on raimei fish location near Kannazuka. It works if you aim at the sky for some reason.
Don't know if it's only me having this.

**Comment by Nigh** [comment]
@Dramorian  set `debug=1` in `setting.ini`, you could check the real time debug info.
it may helps you found the problem.

**Comment by Nigh** [comment]
@Dramorian  if the color of the sky is the same as the fising bar, the script may not work properly.
