### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by PepegaHah** [Nigh/Genshin-fishing#25]
Hello there,

Always having this message when i try to run it. It works, but always giving that error. Possible to fix or block it?

https://ibb.co/LxB1kcQ

**Comment by Nigh** [comment]
@PepegaHah  in `setting.ini`

> specify `mirror=0` to get update from github.com, or `mirror=fastgit`(default) from fastgit.org

or just simply set `autoupdate=0` to block update at all.
