### ISSUE TITLE
请求添加3440*1440的2k宽屏分辨率支持

### ISSUE THREAD

**Issue by HiyoriZeta** [Nigh/Genshin-fishing#27]
请求添加3440*1440的2k宽屏分辨率支持 感谢大佬
![钓鱼 浮漂条](https://user-images.githubusercontent.com/96092020/145910935-e6a61882-e9ed-4bff-b159-9eedbd8030f1.png)
![钓鱼 待机状态](https://user-images.githubusercontent.com/96092020/145910943-6cb9d375-ff7b-4a69-bb53-b69283b1477d.png)
![钓鱼 抛饵状态](https://user-images.githubusercontent.com/96092020/145910945-1737f09a-601f-47ea-9884-71c50fff7b26.png)
![钓鱼 咬钩状态](https://user-images.githubusercontent.com/96092020/145910947-66990a44-177b-4247-bf5e-b1807c0048a1.png)
![钓鱼 全屏截图](https://user-images.githubusercontent.com/96092020/145910948-98cc7100-bc88-4e47-be95-e2614654b2c6.png)

**Comment by Nigh** [comment]
@HiyoriZeta 请测试是否能够正常工作。确认后将会合并至发布版本。
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7739144/GenshinFishing.zip)

**Comment by HiyoriZeta** [comment]
@Nigh  没有问题 可以使用
