### ISSUE TITLE
请求添加3072*1920的分辨率支持

### ISSUE THREAD

**Issue by dmnbme** [Nigh/Genshin-fishing#28]
请求添加3072*1920的分辨率支持，感谢大佬！
![image](https://user-images.githubusercontent.com/89629912/146535251-d07c5f7f-c7ce-46a2-b3ca-5eb28e364c48.png)

**Comment by Nigh** [comment]
非常抱歉，因个人精力有限，无法支持非常规分辨率。建议使用相近的分辨率的窗口模式。
