### ISSUE TITLE
分辨率請求：1440x900 

### ISSUE THREAD

**Issue by seriaati** [Nigh/Genshin-fishing#31]
三個圖標：
![Screenshot (2)](https://user-images.githubusercontent.com/61446626/149043182-4b2b9db4-f3f3-4145-955c-8ff3b92db3de.png)
![Screenshot (3)](https://user-images.githubusercontent.com/61446626/149043315-a2d370f8-c77c-4626-af68-276f4fdc2dc7.png)
![Screenshot (1)](https://user-images.githubusercontent.com/61446626/149043355-121a3275-1f9b-4813-8029-5e9a59db7272.png)

浮標指示器：
![Screenshot (4)](https://user-images.githubusercontent.com/61446626/149043499-6be33347-2fce-4da4-a65e-e6a373e9390b.png)

完整圖片：
![Screenshot (6)](https://user-images.githubusercontent.com/61446626/149043387-c948fec2-b27f-4a62-bb27-2d4d7b314e81.png)

**Comment by Nigh** [comment]
已添加
