### ISSUE TITLE
经常因为提竿超时导致 渊下宫新鱼佛玛洛鳐 捕获失败

### ISSUE THREAD

**Issue by MomentDerek** [Nigh/Genshin-fishing#33]
特指渊下宫新鱼中的稀罕品种，提竿时间非常短，非常容易把鱼放跑，建议把提竿的反应时间缩短

**Comment by Nigh** [comment]
@MomentDerek 在setting.ini中指定`log=3`，可记录详细log。建议进行数次钓鱼后，将在软件目录下生成的`genshinfishing.log`文件上传供分析。初步猜测可能是由于你的帧间距太高导致响应太慢。可以尝试使用较低分辨率的窗口模式。

**Comment by MomentDerek** [comment]
[genshinfishing.log](https://github.com/Nigh/Genshin-fishing/files/8161192/genshinfishing.log)
已上传，我也看了一下，在判断鱼上钩的阶段是700毫秒1帧，那如果有一帧或两帧判断失败了，就可能导致提竿失败
但是在钓鱼阶段，是70ms一帧，可不可以开放一个选项让我们决定每个阶段的判断间距？

**Comment by Nigh** [comment]
@MomentDerek
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/8161643/GenshinFishing.zip)
尝试这个版本。有人上报过因为UI位置的偏移导致无法正确识别到状态图标的问题。不知道你的是不是同样的问题。
检测只设置了速度上限的。实际间隔往往与CPU的机能相关。太长的间隔往往意味着再目标区域没有搜索到目标图像。
