### ISSUE TITLE
分辨率请求 : 2560*1080

### ISSUE THREAD

**Issue by Amarterlus** [Nigh/Genshin-fishing#4]
如题 或者告诉我该改哪几个坐标参数

**Comment by Nigh** [comment]
得重做找图的样本，我还没有实验现有样本能否通过缩放来适配部分分辨率的。

**Comment by Nigh** [comment]
@Amarterlus 请参考 #9 提供素材。

**Comment by Nigh** [comment]
因长时间未给出素材，故关闭此issue.

**Comment by Nigh** [comment]
_Originally posted by @LemnonKeith in https://github.com/Nigh/Genshin-fishing/issues/9#issuecomment-991802945_
![1 (2)](https://user-images.githubusercontent.com/1407471/145772045-2a304ab5-5a0f-4ae7-b173-be97e0f4c2db.PNG)
![2 (2)](https://user-images.githubusercontent.com/1407471/145772053-93d05960-949f-498f-82a7-a03ecc602682.PNG)
![3 (2)](https://user-images.githubusercontent.com/1407471/145772058-dd4a955c-64c3-43ff-850c-40091de01404.PNG)
![4 (2)](https://user-images.githubusercontent.com/1407471/145772061-6f1a1a3b-08e0-45a5-980a-d9272fec2b18.PNG)
![5](https://user-images.githubusercontent.com/1407471/145772063-70ba4672-4658-4afe-a183-18f5d195ef54.PNG)

**Comment by Nigh** [comment]
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7702461/GenshinFishing.zip)
待测试确认。@LemnonKeith

**Comment by LemnonKeith** [comment]
测试通过，除长生仙及雷鸣仙外，其他均以测试，无任何不妥，但压缩包与release版下载的时候稍有不同，压缩包Defender会报毒，release版不会 @Nigh

**Comment by Nigh** [comment]
> 测试通过，除长生仙及雷鸣仙外，其他均以测试，无任何不妥，但压缩包与release版下载的时候稍有不同，压缩包Defender会报毒，release版不会 @Nigh

Defender报毒看心情吧，感觉上差不多一半的时候会报毒，编译过程中就给我报毒了。
