### ISSUE TITLE
手柄1920x1080适配请求

### ISSUE THREAD

**Issue by RJokerD** [Nigh/Genshin-fishing#44]
大佬能做手柄的自动钓鱼吗，Xbox手柄用的是RT键![6.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/c218a74a-c065-43c7-bc60-1388ee1f709c)

![1.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/c2ae11fa-649c-40fb-8087-52a261334ab5)

![5.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/fcceee50-4233-4f4c-aca7-a75723616991)

![4.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/40b24bf6-98f5-428f-9ee1-ae545247f58a)

![3.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/8a4c9cfa-3ba9-403d-af60-02a7d7705799)

![2.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/f161a907-2b81-437c-b9f6-e8282de7824b)

**Comment by RJokerD** [comment]
才发现下边已经有另一个issue了，那我补全一下图片素材吧，这是ns的![NS_4.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/5f6207c4-3224-49e0-8808-103869de496c)

![NS_5.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/78bb1cea-760c-420e-a46e-5b0f10c686cf)

![NS_3.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/c2b596e9-5a0b-4023-8dd8-da8fbad5d98c)

![NS_1.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/af0c6470-254f-450d-8709-7089cdfd7e44)

![NS_2.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/3d67439c-20f7-45d9-b610-18d845da26b4)

**Comment by RJokerD** [comment]
这是PS手柄的，好像和ns的图标一样，而且ns手柄好像不受原神支持，右摇杆不能用来调视角![PS_2.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/c5558c50-6fe8-4021-b9ea-851b194cd4be)

![PS_1.png](https://g![PS_3.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/fb94b78e-5809-4b22-9d45-5a673978a999)

n-fishing/assets/39233981/60cf0e67-e9cf-433b-9d87-1818454ce6be)

![正在上传 PS_3.png…]()

![PS_4.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/20108b6c-1b8f-4e40-bffa-494a462ce1a8)

![PS_5.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/76e81524-2355-463d-b330-60891d0a14ad)

**Comment by RJokerD** [comment]
这是PS手柄的，好像和ns的图标一样，而且ns手柄好像不受原神支持，右摇杆不能用来调视角![PS_1.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/f6976e8e-4480-419d-9bf8-27994cc64cf5)

![PS_3.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/44f36140-13d0-4a8d-9325-5007f6ecd864)

![PS_4.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/ae221081-d667-4236-8063-f531945f5950)

![PS_5.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/191573d3-4759-4b7d-a13f-76e6c300b4c6)

![PS_2.png](https://github.com/Nigh/Genshin-fishing/assets/39233981/02212b46-ff89-4767-8b8e-c5decd8882bb)

**Comment by RJokerD** [comment]
关于手柄按键注入的问题，之前远程串流时遇到过，电脑端安装sunshine，手机端使用moonlight，想要手机正确使用手柄控制电脑，sunshine文档给出的解决方案是这个项目https://github.com/nefarius/ViGEmBus

**Comment by Nigh** [comment]
duplicate with #43
