### ISSUE TITLE
what to do? 

### ISSUE THREAD

**Issue by Lhm543** [Nigh/Genshin-fishing#46]
![image](https://github.com/Nigh/Genshin-fishing/assets/104971290/f809aa5c-72cb-42a9-a0ae-5f921a542f5b)

**Comment by Nigh** [comment]
@Lhm543  Are you running the binary or script?

**Comment by Lhm543** [comment]
binary file

**Comment by Lhm543** [comment]
@Nigh  binary file

**Comment by Lhm543** [comment]
@Nigh I run everything on my computer, everything worked before, but after reinstalling Windows, it stopped working.

**Comment by Nigh** [comment]
@Lhm543 The error message is really weird. Maybe try to download the binary from https://github.com/Nigh/Genshin-fishing/releases again?

**Comment by Lhm543** [comment]
@Nigh It didn't work

**Comment by Nigh** [comment]
No enough info to figure out the problem.
