### ISSUE TITLE
The autohotkey just isn't working at all for me

### ISSUE THREAD

**Issue by ZeLink3123** [Nigh/Genshin-fishing#47]
[genshinfishing.log](https://github.com/Nigh/Genshin-fishing/files/15242486/genshinfishing.log)
This is the log file. I've restarted the software three times just to make sure but it just doesn't work

**Comment by Nigh** [comment]
@ZeLink3123 From the entries on the log file, it seems that the program didn't correctly recognize the skill icons on your game screen. Can you provide a full screen shot of you while fishing (with the fishing skill icon included)?

**Comment by ZeLink3123** [comment]
![Screenshot 2024-05-10 000801](https://github.com/Nigh/Genshin-fishing/assets/141700596/1a6fc058-ac39-4c0f-aeda-2211b74b77d1)
Hi heres the screenshot
Here's the thing tho while trying to fish for this screenshot the autohotkey works now which was kinda weird

**Comment by ZeLink3123** [comment]
ok now it doesn't work when the fish bites. Like it'll click when the fish bites but not when the bar on top appears

**Comment by Nigh** [comment]
> ok now it doesn't work when the fish bites. Like it'll click when the fish bites but not when the bar on top appears

@ZeLink3123 From the log, it looks like the program is not recognizing the state after the fish bites (after the fishing bar appears). Can you provide a screenshot in that state?

Ps. In the previous issues, I noticed that in some client, the color of the fishing bar is different, which is quite weird.
