### ISSUE TITLE
請求分辨率支持2560X1600

### ISSUE THREAD

**Issue by sheaahhoi1** [Nigh/Genshin-fishing#48]
請求分辨率支持2560X1600
![全](https://github.com/Nigh/Genshin-fishing/assets/10239384/4a1663bd-7491-47cc-a788-bb4d2e9d8ffd)
![L](https://github.com/Nigh/Genshin-fishing/assets/10239384/afbc2431-197f-4737-9da9-1ce7cf5fb18d)
![SA](https://github.com/Nigh/Genshin-fishing/assets/10239384/a2b8b41d-49ff-4757-af78-886558030a09)
![SB](https://github.com/Nigh/Genshin-fishing/assets/10239384/ccc38bd3-72ec-48bb-874b-eda05b6ebd07)
![SC](https://github.com/Nigh/Genshin-fishing/assets/10239384/0890593b-7c2a-414f-8f99-6407cdc9bdcf)
![C](https://github.com/Nigh/Genshin-fishing/assets/10239384/b3c71893-31c6-4a34-9f68-288733edd741)

**Comment by sheaahhoi1** [comment]
[[2K]25601600Picture packaging.zip](https://github.com/Nigh/Genshin-fishing/files/15404267/2K.25601600Picture.packaging.zip)
我不確定上方圖片上傳github時會不會強制縮放,所以打成ZIP

**Comment by Nigh** [comment]
@sheaahhoi1 素材已收到，更新后将会在此处上传测试版本，在你本地测试通过后，将会合并入主分支。

**Comment by Nigh** [comment]
@sheaahhoi1 我这边显示器无法测试2560X1600分辨率。请测试以下版本是否能够正常使用。
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/15448047/GenshinFishing.zip)

**Comment by sheaahhoi1** [comment]
功能:是釣起&力度較正?
上述釣起魚兒到力度較正,都可以

下方這種魚反抗較大,力度浮漂 間歇的偏離有效區,但整體仍然尚可
![image](https://github.com/Nigh/Genshin-fishing/assets/10239384/6d0c6048-9379-417e-9444-b176b0949653)

**Comment by Nigh** [comment]
@sheaahhoi1 正常工作即可。
