### ISSUE TITLE
请求添加3840*2160的4k全屏分辨率支持

### ISSUE THREAD

**Issue by FirerainML** [Nigh/Genshin-fishing#6]
请求添加3840*2160的4k全屏分辨率支持，感谢大佬

**Comment by Nigh** [comment]
@FirerainML 参考 #9 提供素材。

**Comment by Nigh** [comment]
@FirerainML 参考下 #11 的方法。不知道是不是这个原因导致的。

**Comment by Nigh** [comment]
3840*2160的支持将于下次更新加入。

**Comment by FirerainML** [comment]
> 3840*2160的支持将于下次更新加入。

辛苦大佬了，这边尝试了大佬说的方法仍然会产生报错，如果只是影响自动更新的话问题应该不大？
![image](https://user-images.githubusercontent.com/89842936/134324291-68a7913b-13d1-4bb6-84c3-26dd02d61f60.png)

**Comment by Nigh** [comment]
[GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7231185/GenshinFishing.zip)
@FirerainML 我这边无法测试4k，麻烦进行下测试，确保使用正常，然后我会进行发布。

**Comment by FirerainML** [comment]
> [GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7231185/GenshinFishing.zip)
> @FirerainML 我这边无法测试4k，麻烦进行下测试，确保使用正常，然后我会进行发布。

大佬，这边我已经测试过了，唯一的问题大概就是有时候鱼咬钩了不会自动开始钓鱼，然后手动点了以后程序也不会自动去控制钓鱼的力度条，必须要手动到那个区间以后软件才会接管控制，其余的已经没问题了，自动更新也是正常的，，辛苦了

**Comment by Nigh** [comment]
> > [GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7231185/GenshinFishing.zip)
> > @FirerainML 我这边无法测试4k，麻烦进行下测试，确保使用正常，然后我会进行发布。
> 
> 大佬，这边我已经测试过了，唯一的问题大概就是有时候鱼咬钩了不会自动开始钓鱼，然后手动点了以后程序也不会自动去控制钓鱼的力度条，必须要手动到那个区间以后软件才会接管控制，其余的已经没问题了，自动更新也是正常的，，辛苦了

你在setting里面添加`debug=1`和`log=2`，看下状态，和每帧的检测时间。

**Comment by FirerainML** [comment]
[genshinfishing.log](https://github.com/Nigh/Genshin-fishing/files/7232689/genshinfishing.log)
大佬你看一下这个文件？我觉得貌似没啥问题

**Comment by Nigh** [comment]
> > [GenshinFishing.zip](https://github.com/Nigh/Genshin-fishing/files/7231185/GenshinFishing.zip)
> > @FirerainML 我这边无法测试4k，麻烦进行下测试，确保使用正常，然后我会进行发布。
> 
> 大佬，这边我已经测试过了，唯一的问题大概就是有时候鱼咬钩了不会自动开始钓鱼，然后手动点了以后程序也不会自动去控制钓鱼的力度条，必须要手动到那个区间以后软件才会接管控制，其余的已经没问题了，自动更新也是正常的，，辛苦了

那我猜测可能是刚开始钓鱼时，没有来得及检测到浮漂条，游标就已经掉到左边去了。我优化一下这里的逻辑就发布吧。
